export const variant = {
  default: 'py-2 px-4 text-white bg-gray-600 rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  none: '',
  joinNow: 'py-4 px-8 text-2xl text-black text-center bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  startChatting: 'py-4 px-8 text-2xl text-white bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  leaveComment: 'py-1.5 px-4 text-lg text-white bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black max-w-min',
  chatTeamListItem: 'cursor-pointer hover:underline active:no-underline hover:text-blue ',
  createTeam: 'fixed right-10 bottom-10 self-end py-4 px-8 text-white text-2xl bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black',
  login: 'bg-white rounded-3xl py-2 px-4 text-black hover:text-gray hover:bg-blue cursor-pointer transition',
  textButton: 'text-xl text-blue cursor-pointer hover:underline',
  getStarted: 'text-xl p-6 bg-blue rounded- hover:bg-blue hover:text-black hover:cursor-pointer transition w-full text-center shadow-sm rounded-lg',
  chatParticipantsBtns: 'text-gray-500 text-xs',
  cancel: 'bg-gray-500 px-4 py-2 rounded-lg hover:bg-white hover:text-black cursor-pointer mx-2',
  home: 'text-white bg-transparent rounded-lg hover:bg-blue cursor-pointer py-2 px-2 transition duration-200',
  chatSend: 'bg-transparent hover:text-blue px-2 border-l-2 border-gray-500 my-1 cursor-pointer',
  signUp: 'text-white cursor-pointer hover:text-blue decoration-solid transition duration-200 cursor-pointer',
  editProfile: 'bg-gray-500 px-4 py-2 rounded-lg text-white hover:bg-blue cursor-pointer mx-2',
  logout: 'bg-gray-500 px-4 py-2 rounded-lg text-white hover:bg-red-900 cursor-pointer mx-2',
};
