export const variant = {
  default: 'py-2 px-4 text-white bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  none: '',
  joinNow: 'py-4 px-8 text-2xl text-white text-center bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  startChatting: 'py-4 px-8 text-2xl text-white bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black shadow-sm',
  leaveComment: 'py-1.5 px-4 text-lg text-white bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black max-w-min',
  chatTeamListItem: 'cursor-pointer hover:underline active:no-underline hover:text-blue',
  createTeam: 'fixed right-10 bottom-10 self-end py-4 px-8 text-white text-2xl bg-dark-blue rounded-lg cursor-pointer transition hover:bg-blue hover:text-black',
  login: 'border-4 border-dark-blue rounded-lg py-1 px-2 hover:text-black hover:bg-blue hover:border-blue cursor-pointer transition',
  textButton: 'text-blue-500 cursor-pointer hover:underline',
  getStarted: 'm-1 text-2xl p-6 bg-dark-blue rounded-lg hover:bg-blue hover:text-black hover:cursor-pointer transition',
  chatParticipantsBtns: 'text-gray-500 text-xs',
  cancel: 'bg-gray-600 px-4 py-2 rounded-lg hover:bg-gray-700 cursor-pointer',
  home: 'text-white bg-transparent rounded-lg hover:bg-blue cursor-pointer py-2 px-2 transition duration-200',
  chatSend: 'bg-transparent hover:text-blue px-2 border-l-2 border-gray-500 my-1 cursor-pointer',
};
